version: "3.9"

services:

  example:
    image: neo4j-example
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/conf/neo4j-example.yml:/application.yml"

  neo4j:
    image: neo4j
    volumes:
      - "${PWD}/data/neo4j/data:/data"
      - "${PWD}/data/neo4j/logs:/logs"
      - "${PWD}/conf/neo4j.conf:/conf/neo4j.conf"
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/secret
